name = "3dlabs"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "3dlabs-db"
database_id = "your-database-id-here"
