name = "3dlabs"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "DB"
database_name = "3dlabs-db"
database_id = "83ef0c1e-ff50-4692-9361-064063243a0f"
