name = "3dlabs"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "3dlabs-db"
database_id = "46c5cad6-05ff-440d-a2da-90a63e646547"
