name = "3dlabs-next"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

# [[d1_databases]]
# binding = "DB"
# database_name = "3dlabs-clients"
# database_id = "83ef0c1e-ff50-4692-9361-064063243a0f"
